name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - run: npm run build
      - name: create npm package
        id: pack
        run: echo ::set-output name=PACKAGE::$(npm -s pack)
      - uses: actions/upload-artifact@v3
        with:
          name: package.tgz
          path: '${{ steps.pack.outputs.PACKAGE }}'
